Repository Tekiter/EZSET, pull requests merged in 2021-04, with the labels that each got.

#163 [Apm] Add Elastic APM
  backend/package.json
  backend/src/init.js
  backend/yarn.lock
  docker-compose.yml
Labels: core, server

#164 [Apm] Change APM_SERVER_URL
  backend/src/index.js
  backend/src/init.js
  docker-compose.yml
Labels: core, server

#165 [Apm] Fix - redirect cors error when socket polling issue
  backend/src/init.js
  backend/src/utils/socket.js
Labels: bug

#169 [#166] fix - socket 400 에러 수정
  frontend/src/main.js
Labels: bug

#170 [#166] fix - socket 리디렉션 에러 수정
  frontend/src/main.js
Labels: bug

#171 [#166] fix - socket 리디렉션 에러 수정
  frontend/src/main.js
Labels: bug

#172 [#166] fix - socket 리디렉션 에러 수정
  frontend/src/main.js
Labels: bug

#176 [#175] penaltyConfig API 리팩토링
  backend/src/api/v2/penaltyconfig.route.js
  backend/src/controller/penaltyConfig.controller.js
  backend/src/dao/penalty.dao.js
  backend/src/dao/penaltyConfig.dao.js
  backend/src/models/Response.js
  backend/src/service/penaltyConfig.service.js
Labels: Penalty, refactoring

#178 [MERGE #177] Penalty 프론트 리팩토링
  backend/src/api/v2/penalty.route.js
  frontend/src/service/penalty.service.js
  frontend/src/service/penaltyConfig.service.js
  frontend/src/views/Manage/PenaltyEdit.vue
  frontend/src/views/Penalty/Penalty.vue
  frontend/src/views/Penalty/PenaltyManage.vue
Labels: refactoring

#182 [#181] 백엔드 Typescript 도입
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/src/api/v1/absencecheck.route.js
  backend/src/api/v1/attendance.route.js
  backend/src/api/v1/index.js
  backend/src/api/v1/penalty.route.js
  backend/src/api/v1/penaltyconfig.route.js
  backend/src/api/v1/schedule.route.js
  backend/src/api/v1/simple.route.js
  backend/src/api/v2/index.js
  backend/src/api/v2/penalty.route.js
  backend/src/api/v2/penaltyconfig.route.js
  backend/src/app.js
  backend/src/app.ts
  backend/src/controller/penalty.controller.js
  backend/src/controller/penaltyConfig.controller.js
  backend/src/dao/penalty.dao.js
  backend/src/dao/penaltyConfig.dao.js
  backend/src/index.js
  backend/src/index.ts
  backend/src/init.js
  backend/src/init.ts
  backend/src/models/Error.js
  backend/src/models/Response.js
  backend/src/models/Schedule.js
  backend/src/models/attendanceDay.js
  backend/src/models/attendanceUser.js
  backend/src/models/officialAbsenceReason.js
  backend/src/service/penalty.service.js
  backend/src/service/penaltyConfig.service.js
  backend/src/utils/api.js
  backend/src/utils/database.js
  backend/src/utils/initialization.js
  backend/src/utils/socket.js
  backend/test/routes.test.js
  backend/tsconfig.json
  backend/yarn.lock
Labels: refactoring

#185 [MERGE #179] Attendance API 리팩토링
  backend/src/api/v2/attendance.route.js
  backend/src/controller/attendance.controller.js
  backend/src/controller/penalty.controller.js
  backend/src/dao/attendance.dao.js
  backend/src/dao/penalty.dao.js
  backend/src/models/attendance.js
  backend/src/service/attendance.service.js
  backend/src/service/penalty.service.js
  backend/src/utils/database.js
  frontend/src/controller/attendance.controller.js
  frontend/src/main.js
Labels: refactoring
